#ifndef ATED_H
#define ATED_H

#define IWPRIV_ERROR								(0)
#define IWPRIV_OK									(1)

#define SOCK_MAX_LISTEN								5
#define CMD_MAXLEN									1024
#define PWR_ARRAY_LEN 								13

#define SIOCIWFIRSTPRIV								(0x8BE0)

#define RTPRIV_IOCTL_E2P        					(SIOCIWFIRSTPRIV + 0x07)
#define RTPRIV_IOCTL_ATE							(SIOCIWFIRSTPRIV + 0x08)
#define RTPRIV_IOCTL_STATISTICS                     (SIOCIWFIRSTPRIV + 0x09)

#define RTPRIV_IOCTL_ATE_SET						0x779
#define RTPRIV_IOCTL_ATE_EFUSE_WRITEBACK			0x765
#define RTPRIV_IOCTL_ATE_WRITECAL					0x766
#define RTPRIV_IOCTL_ATE_SET_DA						0x767
#define RTPRIV_IOCTL_ATE_SET_SA						0x768
#define RTPRIV_IOCTL_ATE_SET_BSSID					0x769
#define RTPRIV_IOCTL_ATE_SET_TX_ANT					0x76A
#define RTPRIV_IOCTL_ATE_SET_TX_CHANNEL				0x76B
#define RTPRIV_IOCTL_ATE_SET_TX_MODE				0x76C
#define RTPRIV_IOCTL_ATE_SET_TX_MCS					0x76D
#define RTPRIV_IOCTL_ATE_SET_TX_BW					0x76E
#define RTPRIV_IOCTL_ATE_SET_TX_GI					0x76F
#define RTPRIV_IOCTL_ATE_SET_TX_LENGTH				0x770
#define RTPRIV_IOCTL_ATE_SET_TX_POW0				0x771
#define RTPRIV_IOCTL_ATE_SET_TX_POW1				0x772
#define RTPRIV_IOCTL_ATE_SET_TX_COUNT				0x773
#define RTPRIV_IOCTL_ATE_SET_TX_FREQOFFSET			0x774
#define RTPRIV_IOCTL_ATE_SET_RX_ANT					0x775
#define RTPRIV_IOCTL_ATE_SET_RX_FER					0x776
#define RTPRIV_IOCTL_ATE_SET_RESETCOUNTER			0x777
#define RTPRIV_IOCTL_ATE_EFUSE_LOAD					0x778
#define RTPRIV_IOCTL_ATE_AUTO_ALC					0x77A
#define RTPRIV_IOCTL_ATE_VCO_CAL					0x77B
#define RTPRIV_IOCTL_ATE_IPG			     		0x77C

#define RTPRIV_IOCTL_ATE_SET_TX_POW_EVAL 			0x77D/*add for 7612E*/

/* Add by Zhao Mengqing, 2017-4-3 */
#define ATE		"ATE=" //must have "="
#define ATEDA   "ATEDA"
#define ATESA   "ATESA"
#define ATEBSSID   "ATEBSSID"
#define ATETXANT    "ATETXANT"
#define ATECHANNEL "ATECHANNEL"
#define ATETXMODE   "ATETXMODE"
#define ATETXMCS    "ATETXMCS"
#define ATETXBW     "ATETXBW"
#define ATETXGI     "ATETXGI"
#define ATETXLEN    "ATETXLEN"
#define ATETXPOW0   "ATETXPOW0"
#define ATETXPOW1   "ATETXPOW1"
#define ATETXCNT    "ATETXCNT"
#define ATETXFREQOFFSET "ATETXFREQOFFSET"
#define ATERXANT    "ATERXANT" 
#define ATERXFER    "ATERXFER"
#define RESETCOUNTER	"ResetCounter"
#define ATEAUTOALC  "ATEAUTOALC"
#define ATEVCOCAL  "ATEVCOCAL"
#define ATEIPG  "ATEIPG"
#define ATETXPOWEVAL "ATETXPOWEVAL"

struct ATE_STR_CMD
{
	int ioctlFlag;
	char* cmdStr;
};

#define ATE_CMD_NUM 22
struct ATE_STR_CMD ateStrCmd[ATE_CMD_NUM] = 
{
	{RTPRIV_IOCTL_ATE_SET, ATE},
	{RTPRIV_IOCTL_ATE_SET_DA, ATEDA},
	{RTPRIV_IOCTL_ATE_SET_SA, ATESA},
	{RTPRIV_IOCTL_ATE_SET_BSSID, ATEBSSID},
	{RTPRIV_IOCTL_ATE_SET_TX_ANT, ATETXANT},
	{RTPRIV_IOCTL_ATE_SET_TX_CHANNEL, ATECHANNEL},
	{RTPRIV_IOCTL_ATE_SET_TX_MODE, ATETXMODE},
	{RTPRIV_IOCTL_ATE_SET_TX_MCS, ATETXMCS},
	{RTPRIV_IOCTL_ATE_SET_TX_BW, ATETXBW},
	{RTPRIV_IOCTL_ATE_SET_TX_GI, ATETXGI},
	{RTPRIV_IOCTL_ATE_SET_TX_LENGTH, ATETXLEN},
	{RTPRIV_IOCTL_ATE_SET_TX_POW0, ATETXPOW0},
	{RTPRIV_IOCTL_ATE_SET_TX_POW1, ATETXPOW1},
	{RTPRIV_IOCTL_ATE_SET_TX_COUNT, ATETXCNT},
	{RTPRIV_IOCTL_ATE_SET_TX_FREQOFFSET, ATETXFREQOFFSET},
	{RTPRIV_IOCTL_ATE_SET_RX_ANT, ATERXANT},
	{RTPRIV_IOCTL_ATE_SET_RX_FER, ATERXFER},
	{RTPRIV_IOCTL_ATE_SET_RESETCOUNTER, RESETCOUNTER},
	{RTPRIV_IOCTL_ATE_AUTO_ALC, ATEAUTOALC},
	{RTPRIV_IOCTL_ATE_VCO_CAL, ATEVCOCAL},
	{RTPRIV_IOCTL_ATE_IPG, ATEIPG},
	{RTPRIV_IOCTL_ATE_SET_TX_POW_EVAL, ATETXPOWEVAL}
};

/* End add */

#endif /* ATED_H */

