#!/usr/bin/env python


bld.SAMBA_LIBRARY('MESSAGING',
	source='messaging.c',
	public_deps='samba-util NDR_IRPC UNIX_PRIVS cluster ndr dcerpc messages_util server_id_db talloc_report',
	private_library=True
	)

if not bld.env.disable_python:
	bld.SAMBA_PYTHON('python_messaging',
		source='pymessaging.c',
		deps='MESSAGING events pyparam_util pytalloc-util',
		realname='samba/messaging.so'
		)

