/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux localhost.localdomain 2.6.35.6-45.fc14.i686 #1 SMP Mon Oct 18 23:56:17 UTC 2010 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Fri Jun 23 09:54:13 HKT 2017"
#define BUILD_ENV_SRCDIR "/mydisk/VR600_ISP/linux_bcm_VR600TTv1/apps/public/samba-3.6.25/source3"
#define BUILD_ENV_BUILDDIR "/mydisk/VR600_ISP/linux_bcm_VR600TTv1/apps/public/samba-3.6.25/source3"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "localhost.localdomain"
#define BUILD_ENV_COMPILER "mips-unknown-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
